services:
  project-nova-frontend:
    build: ./ # Tells Docker to use the Dockerfile in this exact folder
    container_name: project-nova-frontend
    restart: unless-stopped
    networks:
      - app-network
networks:
  app-network:
    external: true
