services:
  testing-site:
    container_name: project-nova-frontend
    build: . # This single dot tells Portainer to use the Dockerfile in this repo
    restart: always
    ports:
      - "3001:80" # Adjust the '80' if your React app uses a different internal port
